Fix ''EPOLLHUP' undeclared' compile error on RHEL7.6
> scst/iscsi-scst/kernel/isert-scst/isert_login.c:843:11: error: 'EPOLLHUP' undeclared (first use in this function)
>   mask |= EPOLLHUP | EPOLLIN;

Seeing above error on "make iscsi" on RHEL7.6.
This did not occur against RHEL7.5 kernel headers.

What I can observe is some of epoll event macros are undefined
when compiling isert_login.c, while EPOLLIN is defined.

Not sure about root cause, but testing each macro instead of
testing EPOLLIN for all event types fixes this.

Signed-off-by: Tomohiro Kusumi <kusumi.tomohiro@osnexus.com>